### ISSUE TITLE
Error in multi.... Module not found.

### ISSUE THREAD

**Issue by saurabBajgain** [manishjanky/ngx-select-dropdown#112]
Angular CLI: 6.0.8
Node: 10.15.0
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      5.0.0-rc.1
@angular/cli                      6.0.8
@angular/material                 5.0.0-rc.1
@ngtools/webpack                  7.2.2
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              5.5.2
typescript                        2.4.2
webpack                           4.28.4
 

**on ng serve:-**
ERROR in multi ./src/styles.css ../node_modules/ngx-select-dropdown/dist/assets/style.css
Module not found: Error: Can't resolve 'F:\xxxx\node_modules\ngx-select-dropdown\dist\assets\style.css' in 'F:\xyz\xxxx'

**Comment by Abdullah8006** [comment]
Any update on why this issue was closed? I am experiencing the same issue.

**Comment by manishjanky** [comment]
@Abdullah8006 update to latest version the style.css is no longer relevant.

**Comment by Chirag1096** [comment]
i am also getting same error after updating npm update, how to resolve this?

**Comment by Chirag1096** [comment]
Hi,
I update by using npm update command after i got the same error. I changed my angular.js file in styles removed F:\xxxx\node_modules\ngx-select-dropdown\dist\assets\style.css', css file is not present there. I saved and stopped my angular cli, again run cli ng serve. It started working fine.

@manishjanky  latest version the style.css is no longer relevant, that's why i removed the last css file of ngx-select-dropdown.
That's all.
