### ISSUE TITLE
Is there any plan to add virtual scroll

### ISSUE THREAD

**Issue by indraraj26** [manishjanky/ngx-select-dropdown#138]
When you have long list it is taking time to open select dropdown

**Comment by manishjanky** [comment]
@indraraj26 there is an option in config `limitTo` can that help. Also let me see what else can I come up with.

**Comment by DiegoSanMo** [comment]
I was trying to use the`limitTo` into the config object but seems that is not taking my limit.
Does someone have the same issue?

**Comment by manishjanky** [comment]
Hi @indraraj26 / @DiegoSanMo First of all sorry for responding after years.. But I was trying to find a way around this... But honestly could not.. Because implementing a custom scroll would mean kind of creating another library.. So I believe if the parent application can use a custom scroll library that is the best possible solution.. 
Still I will see if I can come up with some other possible options..
