### ISSUE TITLE
Dynamically change the multiple to true/false or toggle the list programmatically

### ISSUE THREAD

**Issue by SyedAliHassan90** [manishjanky/ngx-select-dropdown#139]
I need to dynamically change the multiple to true/false based on some conditions. Is there any way to do that? I did it, but it is not working fine with list toggle. Is there any way to toggle the list programmatically?

**Comment by manishjanky** [comment]
@SyedAliHassan90  I think you can do that already.. May be if you create a demo using Stackblitz of the issue you are facing i will be able to help better

**Comment by SyedAliHassan90** [comment]
@manishjanky this is the Stackblitz link: https://stackblitz.com/edit/angular-jd9dbt. 

In my case, When user select "Burns Dalton (SingleSelect)" option then ngx-select-dropdown become single select and when user select other values it becomes multi select.

**Comment by manishjanky** [comment]
@SyedAliHassan90 I don't see a issue with the dropdown here. The problem is with your code where you change it multiselect and single select on each change. and it works as expected according to you code. So whenever you select Burns Dalton it changes to Single Select and if anything else is selected it turns to multi select because `isMultiSelect` variable is updated and this is controlling the multi/single select behaviour of the dropdown.
