### ISSUE TITLE
deselect item after refreshing the list, removes the last item, but it still searchable

### ISSUE THREAD

**Issue by ahmedsherifm** [manishjanky/ngx-select-dropdown#166]
The scenario for what I'm doing:

- I have a component which wraps the ngx-select-dropdown.
- In my view I have 2 dropdown with 2 separate data sources passed to the component
- one of the 2 lists I'm adding more items to it while I'm in the view
- after refreshing the list, it removes the last item from view but that item is still searchable and appear if it matches the search criteria.

**Comment by manishjanky** [comment]
@ForeverDontCare will it be possible for you to create a demo replicating the issue on stackblitz. Also please share the version details..

**Comment by ForeverDontCare** [comment]
@manishjanky sorry for the late response,
here is a POC for what I'm dealing with 
https://angular-b9pl7t.stackblitz.io

if you clicked on 'Add New Item' button it will add a new item to the list and will select it but if you deselect it it will disappear, but you can still search by its number

**Comment by HadyAllam** [comment]
Hello Guys, any update about this issue?!! I am facing it to in my project

**Comment by NouraElarabi** [comment]
Hello everyone, I faced the same issue while working on a project recently. the problem was that limitTo value never gets updated when an item is added to the options list after initialization.
I think this can be fixed from your end @manishjanky .
but for now you can update that value in the config object by hand when you add an item to the array.
also don't forget to use options = [...options,item] instead of options.push(item) and the same goes to updating the config object.

**Comment by manishjanky** [comment]
Let me check this out guys.. 
Also as stated by @NouraElarabi  make sure that when changing options and config you do it this way
``
options = [...options,item] instead of options.push(item) and the same goes to updating the config object.
``

**Comment by manishjanky** [comment]
Update to latest version
