### ISSUE TITLE
List without scrolling option

### ISSUE THREAD

**Issue by aurel282** [manishjanky/ngx-select-dropdown#21]
Hi,

I display a list of 2000 elements, they are all displayed.
I would like to have 10-15-20 and be able to scroll in the list.

I don't see this option?

Thanks,

**Comment by aurel282** [comment]
The line : 
overflow-y:scroll;

In the CSS will solve it ;)

**Comment by manishjanky** [comment]
@aurel282 I know `overflow-y:scroll;` will solve this but i need to decide whether the height of the container be a user configurable property or i can have any value the i feel suits the best. Because without height scroll wont work. 
By the time you can override the css style in your global `style.scc/style.scss` and give a fixed height to the dropdown and use `overflow-y:auto`.

Will update you when i have reached a decision.

**Comment by manishjanky** [comment]
@aurel282 have made the height configurable. Please update to `v0.5.0`.

**Comment by aurel282** [comment]
@manishjanky , Tested and approuved. Thanks for your reactivity.
