### ISSUE TITLE
Ngx-select-dropdown

### ISSUE THREAD

**Issue by sathiyaseelan253** [manishjanky/ngx-select-dropdown#240]
1) How to change the style => color property of scroll bar, gray to blue color in ngx-select-dropdown

![ngx-scroll](https://user-images.githubusercontent.com/46224864/125758548-8a452810-b96c-46d9-91f4-aee987e88dd9.png)

**Comment by ATHI-123** [comment]
@sathiyaseelan253 Did you get it ?

**Comment by manishjanky** [comment]
@sathiyaseelan253 the scroll bar is not controlled by the component. In order to do that you may have use some library to override the default browser scroll bar and that will do the trick for you.
The component does not have those capabilities.
This may help: https://css-tricks.com/almanac/properties/s/scrollbar/
