### ISSUE TITLE
Order of the items not following input list

### ISSUE THREAD

**Issue by pak12** [manishjanky/ngx-select-dropdown#27]
I have a json with 50 items to be used as input options, but the displayed items in the combo box is not in order.
When some items are selected (multi select enabled), the sequences of the order will change too.

**Comment by manishjanky** [comment]
Ok thats not taken into consideration. Will need to have a look if order can be preserved. Will update you soon.

**Comment by manishjanky** [comment]
@totalscoccia sure please send a pull request. Just make sure it passes linting and tests. before sending the pull request you can execute the command `npm run ci`. As the travis build will fail if this command fails.

Thanks

**Comment by totalscoccia** [comment]
@manishjanky Don't know if this is the case also for @pak12, but there are cases when the plain JS array sort() function won't work, due to the fact that the basic behaviour used by browser is to compare characters in the array according to their Unicode code (see https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) .

So my proposal, in order to bypass this limitation, is to add the possibility to define also a custom comparator to use for the sort. In my case, this was done in the following way. In the HTML file the behaviour is basically the same one as before:

` <ngx-select-dropdown [multiple]="false" [(value)]="singleSelect" [config]="config" [options]="options"></ngx-select-dropdown>`

the config options are define as usual in the TS component file:

`config = {
    displayKey:"codDes", 
    search:true,
    customComparator: this.myFunction
  };
  `
the custom function could be something along these lines, or anything that suit the user needs:

` myFunction = function (a, b) {

		let numberA = parseInt(a);
		let numberB = parseInt(b);
		
		// A stricly greater than B, then succeeds
		if (numberA >= numberB) {
			return 1;
		}
		
		// A minor than B, then preceeds
		if (numberA < numberB) {
			return -1;
		}
		
		// A & B are string, then stay like this
		if(numberA === NaN && numberB === NaN) {
			return 0;
		}
		
		// A is a string, then is placed at the left
		if(numberA === NaN) {
			return 1;
		}
		
		// B is a string, and is already at the right side
		if(numberB === NaN) {		
			return 0;
    }
    
    return 0;
	}`

Let me know if this proposal is ok and then I will pull a request from my master (Now I'm not able due to the pending pull from #31 )

**Comment by dcs87** [comment]
Hi @manishjanky, when do you think this will be published? Thx

**Comment by manishjanky** [comment]
Hi @dcs87 by this weekend for sure.

**Comment by manishjanky** [comment]
please update to `v0.7.0`
