### ISSUE TITLE
Do the component have select all / un select all option?

### ISSUE THREAD

**Issue by vinu080890** [manishjanky/ngx-select-dropdown#54]

**Comment by manishjanky** [comment]
No it does not have a select all and deselect option right now. Let me see if i can accommodate the same.

**Comment by DGanapathi** [comment]
Any update on this?

**Comment by lqxchad** [comment]
@manishjanky,

I'm trying to do the same and attempted to implement my own Select All checkbox outside of the dropdown. 
Inside of my checkboxClick code I am just modifying the array that the dropdown is bound:
```
  selectAllClick(event, param) {
    param.Value = event.target.checked ? param.Options : [];
  }
```
but when I set the empty array, the control doesn't update because of the following block in the dropdown's `writeValue` function:

```
            if (this.selectedItems.length === 0) {
                if (Array.isArray(value)) {
                    this.selectedItems = value;
                }
                else {
                    this.selectedItems.push(value);
                }
                this.initDropdownValuesAndOptions();
            }
```
So this works when I check my Select All checkbox. It selects all the items and  but when I deselect, the control doesn't update correctly. The value is written, but the selectedItems property isn't updated accordingly.

Is there a reason that it only updates if the selectedItems.length === 0?

If there's a Select All option coming down the line, that would be great, but I'd also like to at least be able to modify/clear the selection programatically.

**Comment by ashokthrymr** [comment]
Any Update on this feature ?

**Comment by sknagoor** [comment]
We need the select all and deselect all feature

**Comment by dmantelli** [comment]
Any update on this feature? Its the only that it needs to be perfect!

**Comment by orajiakuchibuchi** [comment]
its going to be difficult to add the actual event button in the component UI itself, however to implement it is quite simple,
implement the (change)="selectAllFunction($event)", and simply transfer the option.config.data values to the option.config.model.

**Comment by manishjanky** [comment]
Please update to `v3.2.0` this feature is available, hence closing this thread.
