### ISSUE TITLE
Support for dinamic limitTo config property

### ISSUE THREAD

**Issue by jonbesga** [manishjanky/ngx-select-dropdown#55]
In the `ngx-select-dropdown.component.ts`, line [267](https://github.com/manishjanky/ngx-select-dropdown/blob/master/src/components/ngx-select-dropdown-component/ngx-select-dropdown.component.ts#L267). The current solution works if the previous length was 0. However, If we change, for example, from 1 to 10 as `this.config[key]` already had a previous value (1), the new length (10) won't be applied and the dropdown will still show only the first value of the new options and not the entire amount of options.

Is there a way to have dinamically amount of options or we just have to set `limitTo` property from the beginning to a high value to be able to show all of them?

**Comment by manishjanky** [comment]
Correct me if i'm wrong. So what you want is that if you want to change any config property after the dropdown is already initialized the same should be allowed. If yes the solution to your problem is that.
You can change your config object that see belwo code for example:-
```
config= {
......
limitTo:10,
.....
}
config.limitTo = 20;

config = {...config};
```

This should solve your problem as this will be interpreted as a change in the input property and the config/options will be reset.

Please give it a try and let me know if this works.
