### ISSUE TITLE
Remote Values?

### ISSUE THREAD

**Issue by eltiare** [manishjanky/ngx-select-dropdown#62]
Is it possible to use set the options dynamically based on what the user has typed into the search box? Basically I want to call out to the server for options based on the input. It'd be nice to use this component as a select box for thousands of options (that I don't want to load at first).

**Comment by manishjanky** [comment]
Please correct me if i'm wrong.
So what you want is that instead of local search you want it to be remote i.e as soon as the user enters a search text an api call should be made to fetch the options?

**Comment by eltiare** [comment]
Yes, that is correct.

**Comment by kamal0912** [comment]
Hi @eltiare ,  have you found any solution of this problem yet? 
I am looking for the same functionality that you have mentioned above. Please let me know if there is any alternative.

**Comment by aravinthchellathurai** [comment]
Any update on this?

**Comment by manishjanky** [comment]
Sorry guys for such a long delay.
Here  something that i have been thinking..
The Search functionality part of this component is to filter the existing options. What you guys are seeking is more of a autocomplete functionality along with rest of the features. So that best solution i think will be to have a event `searchTextChanged` emitted and on the same event you can make a api call and get the options and as soon as you get them assign it to the options input. That will do the trick.
Will be soon bringing this in keep a watch.
