### ISSUE TITLE
Doesn't show all list after several times

### ISSUE THREAD

**Issue by vugardadalov** [manishjanky/ngx-select-dropdown#97]
First appears all items.

![image](https://user-images.githubusercontent.com/18144465/53256577-17d29780-367d-11e9-8a07-781f217b1c51.png)

But when I fill other input and back to dropdown half items disappers.
![image](https://user-images.githubusercontent.com/18144465/53256326-72b7bf00-367c-11e9-948f-4a462ee17ef4.png)

**Comment by vugardadalov** [comment]
Is it possible use one config obj for all dropdowns?

**Comment by bingika** [comment]
Were you able to solve this issue?

**Comment by servocoder** [comment]
Got the same issue

**Comment by vugardadalov** [comment]
Unfortunately ((

**Comment by servocoder** [comment]
I found a workaround. You have to remove dropdown from DOM (with `*ngIf` e.g.), and once you put it back all the option become visible. As an option you can have 2 dropdown controls and toggle them in turn.

**Comment by vugardadalov** [comment]
Could you send a short sample?

**Comment by servocoder** [comment]
In my case I have a "main" dropdown with a static preset of options, and depending on the selection the a various number of options was rendered in another dropdown, so that led to the subject issue. So instead of changing options in the same dropdown I have prepared a few dropdowns with a static number of options in the template and show a one of them per time according to the choice in main dropdown.

I haven't provided any code snippets due to my case may be quite specific. But if you think it may help you I could post some code snippets.

**Comment by manishjanky** [comment]
Please use different config objects and options array when using multiple dropdowns in the same view or bind it this way 
```
  get options() {
    return [...this.dropdownOptions];
  }

  get config() {
    return {...this.dropdownConfig};
  }

 <ngx-select-dropdown tabindex="0" (change)="changeValue($event)" [multiple]="true" 
 [(ngModel)]="multiSelect" [config]="config" [options]="options"></ngx-select-dropdown>
```

Please let me know if you still face the issue.. and please try replicating this in a Stackblitz demo as i'm not able to on my end..
