### ISSUE TITLE
duplicate items in search dropdown

### ISSUE THREAD

**Issue by dzenisahusic** [manishjanky/ngx-select-dropdown#99]
On demo:
1 Search for Burns.
2. Select Burns
3. Delete Burns from Search.
4. Choose other item.
5. Search Burns 
Two Burns Dalton are displayed.
Is this Bug or feature?
![dropdownsearch](https://user-images.githubusercontent.com/5814429/54022427-bd642b80-4192-11e9-8458-528004831ea6.png)

**Comment by dzenisahusic** [comment]
I used this component and debug this, the list which is bind doesn't have duplicates, but they are displayed :S  Any updates?

**Comment by karthikrock** [comment]
Probably many users are not noticing this, but this problem does exist. Even though the list we are binding to doesnt have duplicate items, every time an item is selected its duplicated in the dropdown. This is a serious problem and if people noticed this package would not be used at all. PLEASE DO FIX THIS AS A HIGH PRIORITY, otherwise there is no choice but to switch it for a different plugin or write our own. Hope this will be addresses soon, thanks!

**Comment by yokrysty** [comment]
temporary fix:
put the code in your angular AppModule constructor
```
import { SelectDropDownComponent } from 'ngx-select-dropdown';
export class AppModule {
  constructor() {
    const origSelectItem = SelectDropDownComponent.prototype.selectItem;
    SelectDropDownComponent.prototype.selectItem = function (item) {
      const index = this.availableItems.indexOf(item);
      origSelectItem.call(this, item, index);
    };
  }
}
```

**Comment by andresabadia** [comment]
@yokrysty Thanks for the temporary fix.

**Comment by lijo2** [comment]
A new pull request has been submitted for this issue,
https://github.com/manishjanky/ngx-select-dropdown/pull/120

Jonathan

**Comment by manishjanky** [comment]
@lijo2 Thanks for the effort.. Will be releasing a new version soon with the fix.

**Comment by manishjanky** [comment]
Please update to `v1.1.0`
